app_config:
  log_config:
    name: "Local-Gateway"
    env: "DEV"
    level: "debug"
  gin_config:
    address: ":8888"
  eth_config:
    #    endpoint: "https://data-seed-prebsc-2-s3.binance.org:8545/"
    endpoint: "wss://bsc-ws-node.nariox.org:443"
